name: 🧪Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: ⚙️ configure unit test
        run: |
          mkdir -p build/test
          cd build/test
          cmake ../../test
      - name: 🛠️ build unit test
        run: |
          cd build/test
          cmake --build .
      - name: 🧪 run unit test
        run: |
          cd build/test
          ./tests
